Moved stderr redirect to end of commands because bash-language-server got confused

diff --git a/pairon b/pairon
--- a/pairon
+++ b/pairon
@@ -5,13 +5,13 @@ set -e
 . "$(dirname "$(realpath "$0")")/common.sh"
 
 usage() {
-  test -n "$1" && echo >&2 "Error: $1"
-  echo >&2 "
+  test -n "$1" && echo "Error: $1" >&2
+  echo "
 USAGE: $SCRIPT_NAME COMMAND OPTIONS
 
 -- COMMANDS --
 $PLUGINS
-"
+" >&2
   exit 1
 }
 
diff --git a/template/bare-listen b/template/bare-listen
--- a/template/bare-listen
+++ b/template/bare-listen
@@ -12,16 +12,16 @@ export GIT_DIR="$GIT_WORK_TREE/.pairon"
 
 while IFS= read -r line; do
   if test "$line" = "___END_OF_MESSAGE___"; then
-    echo >&2 "=== START PUSHED PATCH ==="
-    echo >&2 "$patch"
-    echo >&2 "=== END PUSHED PATCH ==="
+    echo "=== START PUSHED PATCH ===" >&2
+    echo "$patch" >&2
+    echo "=== END PUSHED PATCH ===" >&2
 
     if { echo "$patch" | git am; }; then
       { echo "$patch";echo ___END_OF_MESSAGE___; } >> "$GIT_DIR/produce"
-      echo >&2 "INFO: Applied patch successfully"
+      echo "INFO: Applied patch successfully" >&2
     else
       git am --abort || true
-      echo >&2 "INFO: Apply patch failed"
+      echo "INFO: Apply patch failed" >&2
       exit 1
     fi
     patch=
